CREATE TABLE `evidence_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`userId` int NOT NULL,
	`youRef` varchar(64) NOT NULL,
	`sourceType` varchar(40) NOT NULL,
	`originalName` varchar(255) NOT NULL,
	`canonicalName` varchar(360) NOT NULL,
	`sourceUrl` text,
	`sourceKey` text,
	`sourceMimeType` varchar(120),
	`sourceHash` varchar(128),
	`eventDate` varchar(64),
	`dateConfidence` varchar(30) NOT NULL DEFAULT 'unknown',
	`organisation` varchar(255),
	`itemType` varchar(120) NOT NULL,
	`sender` varchar(255),
	`recipient` varchar(255),
	`subject` text,
	`extractedText` text,
	`summary` text,
	`deadlinesJson` text NOT NULL,
	`tagsJson` text NOT NULL,
	`relatedYouRefsJson` text NOT NULL,
	`reviewStatus` varchar(30) NOT NULL DEFAULT 'needs_review',
	`reviewNotes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `evidence_items_id` PRIMARY KEY(`id`),
	CONSTRAINT `evidence_items_youRef_unique` UNIQUE(`youRef`)
);
